version: "2"

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: always